// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJ-lXBJm1R4zZvQr1SYNeglKSvTX-f9o',
    appId: '1:724280553469:web:e8afcf92d93b88fef67394',
    messagingSenderId: '724280553469',
    projectId: 'social-media-app-2a140',
    authDomain: 'social-media-app-2a140.firebaseapp.com',
    databaseURL: 'https://social-media-app-2a140-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-app-2a140.firebasestorage.app',
    measurementId: 'G-3MYBJD9RRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmv8GnEhrd4NBqrT6b2SZevCXgUCkCDto',
    appId: '1:724280553469:android:a0a1aba928a116e6f67394',
    messagingSenderId: '724280553469',
    projectId: 'social-media-app-2a140',
    databaseURL: 'https://social-media-app-2a140-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-app-2a140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALrSRgwT5JdN4gGRVCcY9ebvoid1Fi5MY',
    appId: '1:724280553469:ios:12bfb86cf2acddc1f67394',
    messagingSenderId: '724280553469',
    projectId: 'social-media-app-2a140',
    databaseURL: 'https://social-media-app-2a140-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-app-2a140.firebasestorage.app',
    iosClientId: '724280553469-djassgd64juqfru1t7gcvh8hv70l31ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
